<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Content' => 'Tartalom',
    'Created at' => 'Létrehozva',
    'Created by' => 'Létrehozta',
    'Edit post: {title}' => 'Bejegyzés módosítása: {title}',
    'Everybody' => 'Mindenki',
    'If the user is lower in the role-hierarchy, they will not be able to see this post' => 'Az a felhasználó, akinek alacsonyabb van beállítva a hierarchiában, nem láthatja ezt a bejegyzést',
    'Lead' => 'Összefoglaló',
    'New post' => 'Új bejegyzés',
    'Posts' => 'Bejegyzések',
    'Role' => 'Szerepkör',
    'Save' => 'Mentés',
    'Search post by title, or content' => 'Keress cím, vagy tartalom alapján a bejegyzésekben',
    'There are no rule with this name' => 'Nincs ilyen jogosultási kör',
    'This will be shown in the lists, below the title. Max. 300 characters' => 'Ez fog megjelenni a listákban a cím alatt. Maximum 300 karakter',
    'Title' => 'Cím',
    'Update' => 'Módosítás',
    'Updated at' => 'Utoljára módosítva',
    'Updated by' => 'Utoljára módosította',
    'About this post' => 'Tulajdonságok',
    'Are you sure?' => 'Biztos vagy benne?',
    'Delete' => 'Törlés',
    'Download' => 'Letöltés',
    'Print' => 'Nyomtatás',
];
